## Creation of the dataframe

In [82]:
import pandas as pd
import os

In [83]:
# get the directory
dir = os.getcwd()
print('Directory: ', dir)

l = []
count=1


for csv_file in sorted(os.listdir(dir + '/EDA/')):
    if csv_file.endswith(".csv"):
        file_name = os.path.basename(csv_file)
        
        music_ID = int(file_name[0])
        
        my_data = pd.read_csv('EDA/' + file_name, header = None)
        
        VA_std = pd.read_csv(os.getcwd() + '/VA/static_annotations_std.csv', header = None)
        VA_mean = pd.read_csv(os.getcwd() + '/VA/static_annotations.csv', header = None)


        v_std = VA_std.iloc[count][2]
        a_std = VA_std.iloc[count][1]
        v_mean = VA_mean.iloc[count][2]
        a_mean = VA_mean.iloc[count][1]
        count=count+1
        
        subject_ID = my_data.loc[0]

        a = int(subject_ID[1])
        b = int(subject_ID[2])
        c = int(subject_ID[3])
        d = int(subject_ID[4])
        e = int(subject_ID[5])
        f = int(subject_ID[6])
        g = int(subject_ID[7])
        h = int(subject_ID[8])
        i = int(subject_ID[9])
        j = int(subject_ID[10])
        
        # qui il calcolo di tutte le features
        
        data = {'music_ID':[music_ID, music_ID, music_ID, music_ID, music_ID, music_ID, music_ID, music_ID, music_ID, music_ID],
                'subject_ID':[a,b,c,d,e,f,g,h,i,j],
                'valence(mean)':[v_mean,v_mean,v_mean,v_mean,v_mean,v_mean,v_mean,v_mean,v_mean,v_mean],
                'arousal(mean)':[a_dev,a_dev,a_dev,a_dev,a_dev,a_dev,a_dev,a_dev,a_dev,a_dev],
                'valence(std)':[v_std,v_std,v_std,v_std,v_std,v_std,v_std,v_std,v_std,v_std],
                'arousal(std)':[a_mean,a_mean,a_mean,a_mean,a_mean,a_mean,a_mean,a_mean,a_mean,a_mean],
                'feature_x':[0,0,0,0,0,0,0,0,0,0]}
        df = pd.DataFrame(data)
        l.append(df)
        continue

results = pd.concat(l, ignore_index=True)

results

Directory:  /Users/gioelepozzi/Desktop/PMEmo/code/eda_feature_extraction

,music_ID,subject_ID,valence(mean),arousal(mean),valence(std),arousal(std),feature_x
0,1,100179,0.575,0.15,0.160078105936,0.4,0
1,1,100184,0.575,0.15,0.160078105936,0.4,0
2,1,100180,0.575,0.15,0.160078105936,0.4,0
3,1,110448,0.575,0.15,0.160078105936,0.4,0
4,1,100178,0.575,0.15,0.160078105936,0.4,0
5,1,200373,0.575,0.15,0.160078105936,0.4,0
6,1,100181,0.575,0.15,0.160078105936,0.4,0
7,1,100435,0.575,0.15,0.160078105936,0.4,0
8,1,100443,0.575,0.15,0.160078105936,0.4,0
9,1,100177,0.575,0.15,0.160078105936,0.4,0
10,4,200384,0.2875,0.15,0.158607219256,0.2625,0
11,4,100259,0.2875,0.15,0.158607219256,0.2625,0
12,4,100264,0.2875,0.15,0.158607219256,0.2625,0
13,4,100266,0.2875,0.15,0.158607219256,0.2625,0
14,4,110430,0.2875,0.15,0.158607219256,0.2625,0
15,4,100262,0.2875,0.15,0.158607219256,0.2625,0
16,4,100260,0.2875,0.15,0.158607219256,0.2625,0
17,4,100265,0.2875,0.15,0.158607219256,0.2625,0
18,4,100261,0.2875,0.15,0.158607219256,0.2625,0
19,4,100263,0.2875,0.15,0.158607219256,0.2625,0
20,5,100211,0.2,0.15,0.20310096011599998,0.15,0
21,5,100213,0.2,0.15,0.20310096011599998,0.15,0
22,5,100217,0.2,0.15,0.20310096011599998,0.15,0
23,5,100215,0.2,0.15,0.20310096011599998,0.15,0
24,5,100212,0.2,0.15,0.20310096011599998,0.15,0
25,5,100210,0.2,0.15,0.20310096011599998,0.15,0
26,5,100214,0.2,0.15,0.20310096011599998,0.15,0
27,5,100216,0.2,0.15,0.20310096011599998,0.15,0
28,5,110416,0.2,0.15,0.20310096011599998,0.15,0
29,5,200377,0.2,0.15,0.20310096011599998,0.15,0

In [81]:
# export results

results.to_csv('dataframe_EDA.csv')